config/routes.rb
Rails.application.routes.draw do
  get 'calendar/show'

  root to: 'pages#home'

  devise_for :users

  resources :users do
    member do
      put 'toggle', :action => :toggle_approve
    end
  end

  resource :calendar, only: [:show], controller: :calendar
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 50 }, uniqueness: true
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_params
     params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :admin_user,     only: :destroy

  def index
    @users = User.all

  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Matchup!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  #CONTROLLER
  def toggle_approve
    @user = User.find(params[:id])
    @user.toggle!(:admin)
      respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Admin status successfully changed.' }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  private

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
    :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/calendar/show.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-backward"></i>
      <% end %>
      <%= "#{@date.strftime("%B")} #{@date.year}" %>
      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-forward"></i>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= calendar @date do |date| %>
      <%= date.day %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matchup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  </head>

  <body>
  <%= render 'shared/navbar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_pairs.html.erb
<%=
def schedule(array)
   array.push nil if array.size.odd?
   n = array.size
   pivot = array.pop
   games = (n - 1).times.map do
     array.rotate!
     [[array.first, pivot]] + (1...(n / 2)).map { |j| [array[j], array[n - 1 - j]] }
   end
   array.push pivot unless pivot.nil?
   games
 end

students = %w(Maressa Bram Claudia Steve Ilsmarie Jeroen Jesse Han Ann Oliver Adrianna Omar Tim Job Elizabeth Kate Andrei Chris)
teams = schedule(students)

  i = Random.rand(teams.length)
  teams.each_with_index do |day, index|
      if index == i
        day_teams = day.map { |team| "(#{team.first}, #{team.last})" }.join(", ")
        return "Today's team: #{day_teams}"
      end
  end

%>

app/views/pages/_pairs_student.html.erb
<%=
def schedule(array)
   array.push nil if array.size.odd?
   n = array.size
   pivot = array.pop
   games = (n - 1).times.map do
     array.rotate!
     [[array.first, pivot]] + (1...(n / 2)).map { |j| [array[j], array[n - 1 - j]] }
   end
   array.push pivot unless pivot.nil?
   games
 end

students = %w(Maressa Bram Claudia Steve Ilsmarie Jeroen Jesse Han Ann Oliver Adrianna Omar Tim Job Elizabeth Kate Andrei Chris)
teams = schedule(students)

#i = Random.rand(teams.length)
  teams.each_with_index do |day, index|
      if index == 0
        day_teams = day.map { |team| "(#{team.first}, #{team.last})" }.join(", ")
        pair = "Today's team: #{day_teams}"
        return pair
      end
  end

%>

app/views/pages/_panel.html.erb
<div>
<%= link_to "View Calendar", calendar_show_path, class: "btn btn-info" %>
<hr>
<%= render partial: "pairs" %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>


<% if current_user.try(:admin?) %>
<%=render partial: "panel" %>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Matchup", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/users/_user.html.erb
<li>
  <% @user %>
  <%= gravatar_for user, size: 100 %>
  <td><%= user.name %></td>
  <% if current_user.admin %>
    <%= link_to "delete", user, method: :delete,
    data: { confirm: "You sure?" } %>
    <td><%= user.admin %></td>
    <%= link_to "approve", toggle_user_path(user.id), :method => :put, :id => "myonoffswitch" %>


<% end %>
</li>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= render user %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>

app/views/users/toggle_approve.js.erb
$('#myonoffswitch')
<% if @user.admin == true %>
    $(".user-<%= @user.id %> > a").html('true').removeClass('btn-warning').addClass('btn-success')
<% else %>
    $(".user-<%= @user.id %> > a").html('false').removeClass('btn-success').addClass('btn-warning')
<% end %>
$("#user-status-<%= @user.id %>").html("<%= @user.admin %>")